import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>SPIE ANDC</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="m-0">
				{/* HOME PAGE */}
				<section
					id="home"
					className="p-[30px] items-center md:p-[50px] "
					style={{
						backgroundImage: 'url("./image/banner.svg")',
						backgroundSize: "cover",
						backgroundPosition: "center",
					}}
				>
					<div className="grid grid-cols-1">
						<div className="flex flex-col gap-1">
							<h1 className="text-[80px] font-black animate__animated animate__slideInLeft">
								SPIE
							</h1>
							<h2 className="text-2xl p-0 font-bold animate__animated animate__slideInLeft">
								Student Chapter, ANDC
							</h2>
							<p className="text-base animate__animated animate__slideInLeft md:w-[30%]">
								Occaecat adipisicing esse amet aliqua sunt sit non. Incididunt
								laboris duis deserunt anim laboris duis sit amet sunt consequat
								tempor sit. Enim occaecat adipisicing dolore ex ullamco commodo
								incididunt fugiat reprehenderit esse. Labore exercitation
								laboris eu nisi anim ut et elit laboris nulla non.
							</p>
						</div>
					</div>
				</section>
			</main>
			{/* About */}
			<section>
				<div className="about">
					<h1>ABOUT</h1>
					<div className="wrapper">
						<div className="box-area">
							<div className="custom" />
							<div className="box-date">
								<span>2009-2011</span>
							</div>
							<div className="box-text">
								<h2>Lorem ipsum</h2>
								<h3>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</h3>
								<p>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</p>
							</div>
						</div>
						<div className="box-area box-right">
							<div className="custom" />
							<div className="box-date">
								<span>2009-2011</span>
							</div>
							<div className="box-text">
								<h2>Lorem ipsum</h2>
								<h3>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</h3>
								<p>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* ====== TEAM Section Start ====== */}
			<section className="team section" id="Teams">
				<div className="container">
					<div className="row-1">
						<div>
							<h1>MEET SPIE ANDC TEAM</h1>
						</div>
					</div>
					<div className="row-1">
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Prof. Amit Garg <br />
										<span>Faculty Advisor</span>
									</h2>
									<h2>
										<span>Associate Professor ANDC</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className="row">
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Ankush Rana <br />
										<span>President</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fa-brand fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Sakshi Garg <br />
										<span>Vice President</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Kalpajit Roy
										<br />
										<span>Secretary</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className="row">
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Iftekhar Ali <br />
										<span>Treasurer</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Naman Sirohi
										<br />
										<span>Technical Officer</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
						<div className="card">
							<div className="imgBx">
								<img src="#" alt="" />
							</div>
							<div className="content">
								<div className="details">
									<h2>
										Divyansh Rajput <br />
										<span>Editorial Officer</span>
									</h2>
									<div className="data">
										<h3>
											<i className="fab fa-facebook-f" />
											<br />
											<span>Facebook</span>
										</h3>
										<h3>
											<i className="fab fa-instagram" />
											<br />
											<span>Instagram</span>
										</h3>
										<h3>
											<i className="fab fa-twitter" />
											<br />
											<span>Twitter</span>
										</h3>
									</div>
									<div className="actionBtn">
										<button>Follow</button>
										<button>Message</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			{/* ====== TEAM Section end ====== */}

			<section>
				<h1>Contact Us</h1>
			</section>
		</div>
	);
}
