import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TbArrowWaveLeftDown } from "react-icons/tb";
import { BsLinkedin, BsTwitter, BsInstagram } from "react-icons/bs";
import Marquee from "react-fast-marquee";
import andcLogo from "../public/image/logos/andc.png";
import spieLogo from "../public/image/logos/spie.png";
import teamData from "../public/data.json";
export default function Home() {
	return (
		<div className="bg-[#101010]">
			<Head>
				<title>SPIE ANDC</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="m-0">
				{/* HOME PAGE */}
				<section
					id="home"
					className="flex justify-center p-[0.8rem] md:p-[3.125rem] md:py-32 items-end"
					style={{
						background: 'url("./image/banner.svg")',
						backgroundSize: "cover",
						backgroundPosition: "center",
						backgroundAttachment: "fixed",
					}}
				>
					<div className="inline-flex flex-col gap-5 bg-black/70 md:w-[80%] rounded-xl items-center p-10 pt-6 min-h-[80vh] drop-shadow-2xl">
						<div
							className="w-full p-5 flex flex-col rounded-md mb-10 relative"
							style={{
								backgroundImage: 'url("./image/banner.svg")',
								backgroundSize: "cover",
								backgroundPosition: "center",
								backgroundAttachment: "fixed",
							}}
						>
							<div className="hidden absolute right-0 top-0 md:flex p-10 gap-20 justify-center items-center">
								{/* <div className=" h-32 w-32">
									<Image src={spieLogo} />
								</div> */}
								<div className=" h-32 w-32">
									<Image src={andcLogo} />
								</div>
							</div>
							<h1 className="text-[5rem] md:text-[10rem] font-black">SPIE</h1>
							<h2 className="text-2xl p-0 font-bold">
								The Student Chapter of
								<br />
								Acharya Narendra Dev College, University of Delhi
							</h2>
						</div>
						<div>
							<p className="flex items-end text-2xl text-justify">
								Occaecat adipisicing esse amet aliqua sunt sit non. Incididunt
								laboris duis deserunt anim laboris duis sit amet sunt consequat
								tempor sit. Enim occaecat adipisicing dolore ex ullamco commodo
								incididunt fugiat reprehenderit esse. Labore exercitation
								laboris eu nisi anim ut et elit laboris nulla non.
							</p>
						</div>
						<div className="relative bg-white text-white/0 h-[0.1rem] w-full rounded-full my-5">
							.
						</div>
						<div className="">
							<div className="flex flex-row-reverse">
								<TbArrowWaveLeftDown className="-rotate-45 h-20 w-20" />
							</div>
							<h2 className="text-[5rem] font-black flex flex-col items-end">
								About
								<div className="text-[1.5rem]">SPIE ANDC</div>
							</h2>
							<p className="text-xl flex items-end text-justify mt-5  ">
								Occaecat adipisicing esse amet aliqua sunt sit non. Incididunt
								laboris duis deserunt anim laboris duis sit amet sunt consequat
								tempor sit. Enim occaecat adipisicing dolore ex ullamco commodo
								incididunt fugiat reprehenderit esse. Labore exercitation
								laboris eu nisi anim ut et elit laboris nulla non. Occaecat
								adipisicing esse amet aliqua sunt sit non. Incididunt laboris
								duis deserunt anim laboris duis sit amet sunt consequat tempor
								sit. Enim occaecat adipisicing dolore ex ullamco commodo
								incididunt fugiat reprehenderit esse. Labore exercitation
								laboris eu nisi anim ut et elit laboris nulla non.
							</p>
						</div>
					</div>
				</section>
			</main>
			{/* About */}
			{/* <section>
				<div className="about">
					<h1>ABOUT</h1>
					<div className="wrapper">
						<div className="box-area">
							<div className="custom" />
							<div className="box-date">
								<span>2009-2011</span>
							</div>
							<div className="box-text">
								<h2>Lorem ipsum</h2>
								<h3>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</h3>
								<p>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</p>
							</div>
						</div>
						<div className="box-area box-right">
							<div className="custom" />
							<div className="box-date">
								<span>2009-2011</span>
							</div>
							<div className="box-text">
								<h2>Lorem ipsum</h2>
								<h3>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</h3>
								<p>
									quibusdam, recusandae sit vero unde, sed, incidunt et ea quo
									dolore laudantium consectetur!
								</p>
							</div>
						</div>
					</div>
				</div>
			</section> */}

			{/* ====== TEAM Section Start ====== */}
			<section
				className="team bg-black rounded-[4rem] -translate-y-10 flex-col py-32 flex gap-32 justify-center items-center"
				id="Teams"
			>
				<h2 className="text-[5rem] md:text-[8rem]">
					<Marquee gradient={false} speed={200}>
						MEET THE
						<div className="text-[#b91c1c] underline decoration-wavy decoration-2 decoration-red-700 underline-offset-8 mx-3">
							SPIE ANDC
						</div>
						TEAM <div className="text-red-700">.</div>
					</Marquee>
				</h2>
				<div className="grid grid-cols-1 md:grid-cols-3 gap-20 justify-center items-center">
					{teamData["team"].map((item, iter) => {
						return (
							<div key={iter}>
								<div className="card">
									<div className="imgBx">
										<img src="#" alt="" />
									</div>
									<div className="content">
										<div className="details">
											<h2>
												{item.name} <br />
												<span>{item.position}</span>
											</h2>
											<div className="data grid grid-cols-3">
												<h3>
													<BsLinkedin className="h-10 w-10" />
													Linkedin
												</h3>
												<h3>
													<BsInstagram className="h-10 w-10" />
													Instagram
												</h3>
												<h3>
													<BsTwitter className="h-10 w-10" />
													Twitter
												</h3>
											</div>
										</div>
									</div>
								</div>
							</div>
						);
					})}
				</div>
			</section>
			{/* ====== TEAM Section end ====== */}

			<section>
				<h1>Contact Us</h1>
			</section>
		</div>
	);
}
